# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dlineage

pool:
  vmImage: ubuntu-latest

steps:  
  - task: Bash@3
    displayName: 'build'
    inputs:
      targetType: filePath
      filePath: './build_dlineage.sh'
  - task: GitHubRelease@1
    inputs:
      gitHubConnection: 'shenhuan2021'
      repositoryName: 'sqlparser/gsp_demo_java'
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'gitTag'
      title: 'gudusoft.dlineage'
      releaseNotesFilePath: '$(system.defaultworkingdirectory)/dlienagezip/*.zip'
      changeLogCompareToRelease: 'lastFullRelease'
      changeLogType: 'commitBased'

