package demos.visitors;

// JUnit 4 imports (compatible with existing project)
import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

import javax.xml.XMLConstants;
import javax.xml.transform.stream.StreamSource;
import javax.xml.validation.Schema;
import javax.xml.validation.SchemaFactory;
import javax.xml.validation.Validator;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.StringReader;

import gudusoft.gsqlparser.EDbVendor;
import gudusoft.gsqlparser.TGSqlParser;

/**
 * JUnit 4 tests to verify that the comprehensive XSD schema (sqlschema_comprehensive.xsd) 
 * correctly validates XML output generated by xmlVisitor.java
 */
public class XmlSchemaValidationTest {
    
    private Schema schema;
    private String xsdPath;
    private TGSqlParser parser;

    @Before
    public void setUp() throws Exception {
        // Use the comprehensive XSD schema
        File xsdFile = new File("gsp_java_core/doc/xml/sqlschema_comprehensive.xsd");
        if (!xsdFile.exists()) {
            xsdFile = new File("../gsp_java_core/doc/xml/sqlschema_comprehensive.xsd");
        }
        xsdPath = "file:///" + xsdFile.getAbsolutePath().replace('\\', '/');
        
        // Create schema from comprehensive XSD
        SchemaFactory factory = SchemaFactory.newInstance(XMLConstants.W3C_XML_SCHEMA_NS_URI);
        schema = factory.newSchema(new StreamSource(xsdPath));
        
        // Initialize SQL parser
        parser = new TGSqlParser(EDbVendor.dbvoracle);
    }

    @Test
    public void testSimpleSelectStatement() throws Exception {
        String sql = "SELECT id, name FROM users WHERE active = 1";
        
        parser.sqltext = sql;
        int result = parser.parse();
        assertEquals("SQL parsing should succeed", 0, result);
        
        // Generate XML using xmlVisitor
        xmlVisitor visitor = new xmlVisitor(xsdPath);
        visitor.run(parser);
        
        String xml = visitor.getFormattedXml();
        assertNotNull("Generated XML should not be null", xml);
        assertFalse("Generated XML should not be empty", xml.trim().isEmpty());
        
        // Validate against comprehensive schema
        assertTrue("XML should be valid against comprehensive schema", validateXmlAgainstSchema(xml));
        
        // Verify XML contains expected elements
        assertTrue("XML should contain select_statement", xml.contains("select_statement"));
        assertTrue("XML should contain query_expression", xml.contains("query_expression"));
        assertTrue("XML should contain column references", xml.contains("column_referenced_expr"));
    }

    @Test
    public void testCreateSequenceStatement() throws Exception {
        String sql = "CREATE SEQUENCE test_seq START WITH 1 INCREMENT BY 1 CACHE 20";
        
        parser.sqltext = sql;
        int result = parser.parse();
        assertEquals("SQL parsing should succeed", 0, result);
        
        xmlVisitor visitor = new xmlVisitor(xsdPath);
        visitor.run(parser);
        
        String xml = visitor.getFormattedXml();
        assertNotNull("Generated XML should not be null", xml);
        
        // Validate against comprehensive schema
        assertTrue("XML should be valid against comprehensive schema", validateXmlAgainstSchema(xml));
        
        // Verify sequence-specific elements
        assertTrue("XML should contain create_sequence_statement", xml.contains("create_sequence_statement"));
        assertTrue("XML should contain sequence_name", xml.contains("sequence_name"));
    }

    @Test
    public void testComplexStatements() throws Exception {
        // Test various statement types that should be covered by comprehensive schema
        String[] sqlStatements = {
            "DROP TABLE test_table",
            "CREATE INDEX idx_test ON test_table (column1)",
            "INSERT INTO test_table VALUES (1, 'test')",
            "UPDATE test_table SET column1 = 'updated' WHERE id = 1",
            "DELETE FROM test_table WHERE id = 1"
        };
        
        for (String sql : sqlStatements) {
            parser.sqltext = sql;
            int result = parser.parse();
            assertEquals("SQL parsing should succeed for: " + sql, 0, result);
            
            xmlVisitor visitor = new xmlVisitor(xsdPath);
            visitor.run(parser);
            
            String xml = visitor.getFormattedXml();
            assertNotNull("Generated XML should not be null for: " + sql, xml);
            assertTrue("XML should be valid against comprehensive schema for: " + sql, 
                      validateXmlAgainstSchema(xml));
        }
    }

    @Test
    public void testSchemaCompleteness() throws Exception {
        // Test that comprehensive schema is larger than improved schema
        File comprehensiveFile = new File("gsp_java_core/doc/xml/sqlschema_comprehensive.xsd");
        if (!comprehensiveFile.exists()) {
            comprehensiveFile = new File("../gsp_java_core/doc/xml/sqlschema_comprehensive.xsd");
        }
        File originalFile = new File("gsp_java_core/doc/xml/sqlschema.xsd");
        if (!originalFile.exists()) {
            originalFile = new File("../gsp_java_core/doc/xml/sqlschema.xsd");
        }
        
        assertTrue("Comprehensive schema file should exist", comprehensiveFile.exists());
        assertTrue("Original schema file should exist", originalFile.exists());
        
        // Verify comprehensive schema is larger (indicating it includes more elements)
        long comprehensiveSize = comprehensiveFile.length();
        long originalSize = originalFile.length();
        
        assertTrue("Comprehensive schema should be larger than original", 
                  comprehensiveSize > originalSize);
        
        System.out.println("Schema size comparison:");
        System.out.println("  Original: " + originalSize + " bytes");
        System.out.println("  Comprehensive: " + comprehensiveSize + " bytes");
        System.out.println("  Coverage: " + (comprehensiveSize * 100 / originalSize) + "%");
    }
    
    private boolean validateXmlAgainstSchema(String xml) {
        try {
            Validator validator = schema.newValidator();
            validator.validate(new StreamSource(new StringReader(xml)));
            return true;
        } catch (Exception e) {
            System.err.println("XML Validation Error: " + e.getMessage());
            System.err.println("XML Content: " + xml);
            return false;
        }
    }
    
    // Additional helper methods for testing edge cases
    @Test
    public void testXmlVisitorCoverage() throws Exception {
        // Test various SQL constructs to ensure comprehensive coverage
        // Note: Using Oracle-compatible syntax since parser is initialized with dbvoracle
        String[] testCases = {
            "CREATE TABLE test (id INT PRIMARY KEY, name VARCHAR(50))",
            "ALTER TABLE test ADD email VARCHAR(100)",  // Oracle syntax (no COLUMN keyword)
            "CREATE VIEW test_view AS SELECT * FROM test",
            "CREATE OR REPLACE FUNCTION test_func RETURN INT AS BEGIN RETURN 1; END;"  // Oracle syntax
        };
        
        int validCount = 0;
        int totalCount = testCases.length;
        
        for (String sql : testCases) {
            try {
                parser.sqltext = sql;
                int result = parser.parse();
                
                if (result == 0) { // Only test if parsing succeeds
                    xmlVisitor visitor = new xmlVisitor(xsdPath);
                    visitor.run(parser);
                    
                    String xml = visitor.getFormattedXml();
                    if (validateXmlAgainstSchema(xml)) {
                        validCount++;
                    }
                }
            } catch (Exception e) {
                // Log but don't fail - some SQL may not be supported by parser
                System.out.println("Skipping test case due to parsing issue: " + sql);
            }
        }
        
        System.out.println("Validation Coverage: " + validCount + "/" + totalCount + " test cases passed");
        assertTrue("At least half of test cases should validate successfully", 
                  validCount >= totalCount / 2);
    }
} 